config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  get 'students/new'
  #devise_for :users
  root to: 'home#index'
  get 'about', to: 'home#about'

  get 'courses/new', to: 'courses#new'
  get 'courses/index', to: 'courses#index'

  get 'login', to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'course_enroll', to: 'student_courses#create'

  resources :students, except: [:destroy]
  # root 'home#index' 

  # namespace :api do
  #   namespace :v1 do
  #     resources :sessions, only: [:create,:destroy]
  #     devise_scope :user do
  #       post '/login' => 'sessions#create'
  #       delete '/logout' => 'sessions#destroy'
  #     end
  #     # get '/user_list' => 'users#index' 
  #     # get '/show_user' => 'users#show'
  #     get '/users' => 'users#index' 
  #     post '/create_user' => 'users#create_user'
  #     post '/update_user' => 'users#update'
  #     post '/deactivate_user' => 'users#deactivate_user'
  #     post '/delete_user' => 'users#delete_user'

  #     get '/tags' => 'tags#index'
  #     post '/create_tag' => 'tags#create_tag'
  #     post '/update_tag' => 'tags#update_tag'
  #     post '/delete_tag' => 'tags#delete_tag'
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {minimum: 3, maximun: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update]
  skip_before_action :require_student, only: [:new, :create]
  before_action :only_current_student, only: [:edit, :update]


  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "You have successfully signed up."
      redirect_to @student
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile."
      redirect_to @student
    else
      render 'edit'
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def only_current_student
    if current_student != @student
      flash[:notice] = "You can edit only your profile"
      redirect_to student_path(current_student)
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? "Sign up" : "Edit Profile"%></h3>
        <div class="row">
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">  
                <%= f.text_field :name, placeholder: "Enter full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter email", autofocus: true %>
                <%= f.label :email, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Choose Password", autofocus: true %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Confirm Password", autofocus: true %>
                <%= f.label :password_confirmation, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? "Sign up" : "Submit", class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Students List</h3>
  </div>
</div>

<div class="row">
  <% @students.each do |stu| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= stu.name %></span>
          <p>Email: <%= stu.email %></p>
          <p> Course Details </p>
        </div>
        <div class="card-action">
          <%= link_to "View Profile", student_path(stu) %>
        </div>
      </div>
    </div>
  <% end%>  
</div>

app/views/students/new.html.erb
<% if @student.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(@student.errors.count, "error") %></strong> occured
            <ul>
              <% @student.errors.full_messages.each do |error| %>
              <li><%= error %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>    
  </div> 
<% end %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Sign up!</h3>
        <div class="row">
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">  
                <%= f.text_field :name, placeholder: "Enter full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter email", autofocus: true %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.submit "Submit", class: "waves-effect waves-light btn" %>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="row sign-up-form">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <p>Email: <%= @student.email %></p>
        <p> Course Details </p>
      </div>
      <div class="card-action">
        <p>Current Enrollements:
          <% if @student.courses.empty? %>
            None
          <% else %>
            <ul>
              <% @student.courses.each do |sc| %>
                <li><%= sc.name %></li>
              <% end %>
            </ul>
          <% end %>
        </p>
      </div>
    </div>
    <% if current_student == @student %>
      <%= link_to '<i class="material-icons right">create</i>Edit Profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
    <% end %>
  </div>
</div>