config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  get 'students/new'
  #devise_for :users
  root to: 'home#index'
  get 'about', to: 'home#about'

  get 'courses/new', to: 'courses#new'
  get 'courses/index', to: 'courses#index'

  get 'login', to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'course_enroll', to: 'student_courses#create'

  resources :students, except: [:destroy]
  # root 'home#index' 

  # namespace :api do
  #   namespace :v1 do
  #     resources :sessions, only: [:create,:destroy]
  #     devise_scope :user do
  #       post '/login' => 'sessions#create'
  #       delete '/logout' => 'sessions#destroy'
  #     end
  #     # get '/user_list' => 'users#index' 
  #     # get '/show_user' => 'users#show'
  #     get '/users' => 'users#index' 
  #     post '/create_user' => 'users#create_user'
  #     post '/update_user' => 'users#update'
  #     post '/deactivate_user' => 'users#deactivate_user'
  #     post '/delete_user' => 'users#delete_user'

  #     get '/tags' => 'tags#index'
  #     post '/create_tag' => 'tags#create_tag'
  #     post '/update_tag' => 'tags#update_tag'
  #     post '/delete_tag' => 'tags#delete_tag'
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_student
  
  def new
  end

  def index
    @courses = Course.all
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Course List</h3>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %> : <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !(current_student.courses.include?(course)) %>
            <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <a href="#">Info</a>
        </div>
      </div>
    </div>
  <% end%>  
</div>

<div class="row">
  
</div>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>