config/routes.rb
Rails.application.routes.draw do
  
  get 'students/index'
  get 'students/new'
  #devise_for :users
  root to: 'home#index'
  get 'about', to: 'home#about'

  get 'courses/new', to: 'courses#new'
  get 'courses/index', to: 'courses#index'

  get 'login', to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'course_enroll', to: 'student_courses#create'

  resources :students, except: [:destroy]
  # root 'home#index' 

  # namespace :api do
  #   namespace :v1 do
  #     resources :sessions, only: [:create,:destroy]
  #     devise_scope :user do
  #       post '/login' => 'sessions#create'
  #       delete '/logout' => 'sessions#destroy'
  #     end
  #     # get '/user_list' => 'users#index' 
  #     # get '/show_user' => 'users#show'
  #     get '/users' => 'users#index' 
  #     post '/create_user' => 'users#create_user'
  #     post '/update_user' => 'users#update'
  #     post '/deactivate_user' => 'users#deactivate_user'
  #     post '/delete_user' => 'users#delete_user'

  #     get '/tags' => 'tags#index'
  #     post '/create_tag' => 'tags#create_tag'
  #     post '/update_tag' => 'tags#update_tag'
  #     post '/delete_tag' => 'tags#delete_tag'
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Techy Content</h5>
        <p class="grey-text text-lighten-4">Dev content</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2021 My University
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
      <li><%= link_to "View Profile", student_path(current_student) %></li>
    <% end %>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>

  <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
      <li><%= link_to "View Profile", student_path(current_student) %></li>
    <% end %>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "SK University", root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to "Courses", courses_index_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Students", students_path %></li>
          <%end%>
          <li><%= link_to 'About', about_path %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to "Courses", root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Students", students_path %></li>
          <%end%>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, msg|%>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel green lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= msg %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <main>
      <div class="container"> 
        <%= yield %>
      </div>
    </main>

    <%= render 'layouts/footer' %>

  </body>
</html>